spring.application.name=course-service
spring.datasource.url=jdbc:mariadb://course-db:3306/coursedb
spring.datasource.username=courseuser
spring.datasource.password=coursepass
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

server.port=8080
