version: 0.0
os: linux

files:
  - source: target/
    destination: /opt/university

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60

  AfterInstall:
    - location: scripts/install.sh
      timeout: 120

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60

  ValidateService:
    - location: scripts/healthcheck.sh
      timeout: 60
