version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  build:
    commands:
      - cd monolith-ec2
      - mvn clean package -DskipTests

artifacts:
  files:
    - monolith-ec2/target/*.jar
    - monolith-ec2/appspec.yml
    - monolith-ec2/scripts/**/*
