spring.application.name=enrollment-service
spring.datasource.url=jdbc:mariadb://enrollment-db:3306/enrollmentdb
spring.datasource.username=enrolluser
spring.datasource.password=enrollpass

spring.jpa.hibernate.ddl-auto=update
server.port=8080
