spring.application.name=student-service
spring.datasource.url=jdbc:mariadb://student-db:3306/studentdb
spring.datasource.username=studentuser
spring.datasource.password=studentpass
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

server.port=8080
